export type BoardVideo = { id: number; title: string; src: string };

export const boardVideos: BoardVideo[] = [
  { id: 1, title: "Ameerh Reviews Drifting Vf Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/ameerh-reviews-drifting-vf-captioned.mp4" },
  { id: 2, title: "Ameerhs Phone V5 Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/ameerhs-phone-v5-captioned.mp4" },
  { id: 3, title: "Aston Martin Db9 V4 Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/aston-martin-db9-v4-captioned.mp4" },
  { id: 4, title: "Aston Vs Mercedes V8", src: "https://d6lso8oygmnu9.cloudfront.net/videos/aston-vs-mercedes-v8.mp4" },
  { id: 5, title: "Attributes Of The Successful V2", src: "https://d6lso8oygmnu9.cloudfront.net/videos/attributes-of-the-successful-v2.mp4" },
  { id: 6, title: "Aubameyang Final Cta", src: "https://d6lso8oygmnu9.cloudfront.net/videos/aubameyang-final-cta.mp4" },
  { id: 7, title: "Banana Milk Pod", src: "https://d6lso8oygmnu9.cloudfront.net/videos/banana-milk-pod.mp4" },
  { id: 8, title: "Being Grateful Final Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/being-grateful-final-captioned.mp4" },
  { id: 9, title: "Being Realistic V8 Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/being-realistic-v8-captioned.mp4" },
  { id: 10, title: "Best Budget Plane 10m", src: "https://d6lso8oygmnu9.cloudfront.net/videos/best-budget-plane-10m.mp4" },
  { id: 11, title: "Best Seat Corporate Jet", src: "https://d6lso8oygmnu9.cloudfront.net/videos/best-seat-corporate-jet.mp4" },
  { id: 12, title: "Biggest Hurdles", src: "https://d6lso8oygmnu9.cloudfront.net/videos/biggest-hurdles.mp4" },
  { id: 13, title: "Breakdown Jet Sizes", src: "https://d6lso8oygmnu9.cloudfront.net/videos/breakdown-jet-sizes.mp4" },
  { id: 14, title: "Bugatti Bollide Fv Captioned 4ozp", src: "https://d6lso8oygmnu9.cloudfront.net/videos/bugatti-bollide-fv-captioned-4ozp.mp4" },
  { id: 15, title: "Bugatti Bollide Fv Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/bugatti-bollide-fv-captioned.mp4" },
  { id: 16, title: "Building The Naran V4 Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/building-the-naran-v4-captioned.mp4" },
  { id: 17, title: "Buying A Buggatti Vf Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/buying-a-buggatti-vf-captioned.mp4" },
  { id: 18, title: "Buying Jet Crypto", src: "https://d6lso8oygmnu9.cloudfront.net/videos/buying-jet-crypto.mp4" },
  { id: 19, title: "Calibre Of Clients", src: "https://d6lso8oygmnu9.cloudfront.net/videos/calibre-of-clients.mp4" },
  { id: 20, title: "Carrera Gt Tour V4 Captioned", src: "https://d6lso8oygmnu9.cloudfront.net/videos/carrera-gt-tour-v4-captioned.mp4" },
  { id: 21, title: "Clip 4", src: "https://d6lso8oygmnu9.cloudfront.net/videos/clip-4.mp4" },
  { id: 22, title: "Expanding Tjb", src: "https://d6lso8oygmnu9.cloudfront.net/videos/expanding-tjb.mp4" },
  { id: 23, title: "Fastest Corporate Jet", src: "https://d6lso8oygmnu9.cloudfront.net/videos/fastest-corporate-jet.mp4" },
  { id: 24, title: "Favourite Model Each Brand", src: "https://d6lso8oygmnu9.cloudfront.net/videos/favourite-model-each-brand.mp4" },
  { id: 25, title: "Follow Your Passion", src: "https://d6lso8oygmnu9.cloudfront.net/videos/follow-your-passion.mp4" },
  { id: 26, title: "Food On Plane", src: "https://d6lso8oygmnu9.cloudfront.net/videos/food-on-plane.mp4" },
  { id: 27, title: "Formation Of Tjb", src: "https://d6lso8oygmnu9.cloudfront.net/videos/formation-of-tjb.mp4" },
  { id: 28, title: "Get Better At Sales", src: "https://d6lso8oygmnu9.cloudfront.net/videos/get-better-at-sales.mp4" },
  { id: 29, title: "How To Be Pj Broker", src: "https://d6lso8oygmnu9.cloudfront.net/videos/how-to-be-pj-broker.mp4" },
  { id: 30, title: "I Also Sell Helicopters", src: "https://d6lso8oygmnu9.cloudfront.net/videos/i-also-sell-helicopters.mp4" },
  { id: 31, title: "Impact Social Media", src: "https://d6lso8oygmnu9.cloudfront.net/videos/impact-social-media.mp4" },
  { id: 32, title: "Importance Business Card", src: "https://d6lso8oygmnu9.cloudfront.net/videos/importance-business-card.mp4" },
  { id: 33, title: "Jet Call In Video", src: "https://d6lso8oygmnu9.cloudfront.net/videos/jet-call-in-video.mp4" },
  { id: 34, title: "Jumpstart Your Career", src: "https://d6lso8oygmnu9.cloudfront.net/videos/jumpstart-your-career.mp4" },
  { id: 35, title: "Less Turbulence", src: "https://d6lso8oygmnu9.cloudfront.net/videos/less-turbulence.mp4" },
  { id: 36, title: "Lse Students Visit", src: "https://d6lso8oygmnu9.cloudfront.net/videos/lse-students-visit.mp4" },
  { id: 37, title: "Message To Fans", src: "https://d6lso8oygmnu9.cloudfront.net/videos/message-to-fans.mp4" },
  { id: 38, title: "My Dream Cars V5 Captioned Mp4", src: "https://d6lso8oygmnu9.cloudfront.net/videos/my-dream-cars-v5-captioned-mp4.mp4" },
  { id: 39, title: "Never Giving Up", src: "https://d6lso8oygmnu9.cloudfront.net/videos/never-giving-up.mp4" },
  { id: 40, title: "Never Say Its Done", src: "https://d6lso8oygmnu9.cloudfront.net/videos/never-say-its-done.mp4" },
  { id: 41, title: "New Year 2025", src: "https://d6lso8oygmnu9.cloudfront.net/videos/new-year-2025.mp4" },
  { id: 42, title: "Owning A Jet", src: "https://d6lso8oygmnu9.cloudfront.net/videos/owning-a-jet.mp4" },
  { id: 43, title: "Professional Luck", src: "https://d6lso8oygmnu9.cloudfront.net/videos/professional-luck.mp4" },
  { id: 44, title: "Replica Model Jet", src: "https://d6lso8oygmnu9.cloudfront.net/videos/replica-model-jet.mp4" },
  { id: 45, title: "Rolls Royce Fact", src: "https://d6lso8oygmnu9.cloudfront.net/videos/rolls-royce-fact.mp4" },
  { id: 46, title: "Selling 19m Jet 8 Hours", src: "https://d6lso8oygmnu9.cloudfront.net/videos/selling-19m-jet-8-hours.mp4" },
  { id: 47, title: "Tours Showroom London", src: "https://d6lso8oygmnu9.cloudfront.net/videos/tours-showroom-london.mp4" },
  { id: 48, title: "Younger Gen Fuselage", src: "https://d6lso8oygmnu9.cloudfront.net/videos/younger-gen-fuselage.mp4" },
  { id: 49, title: "Client schedule", src: "https://d6lso8oygmnu9.cloudfront.net/videos/client-schedule-v5.mp4" },
  { id: 50, title: "Customer Service", src: "https://d6lso8oygmnu9.cloudfront.net/videos/customer-service-v5.mp4" },
  { id: 51, title: "Discipline", src: "https://d6lso8oygmnu9.cloudfront.net/videos/discipline-fv-captioned.mp4" },
  { id: 52, title: "FIlling up Jesko", src: "https://d6lso8oygmnu9.cloudfront.net/videos/filling-up-jesko-revised-final.mp4" },
  { id: 53, title: "Fastest BMW", src: "https://d6lso8oygmnu9.cloudfront.net/videos/fastest-bmw-fv.mp4" },
  { id: 54, title: "Favourite thing about Jesko", src: "https://d6lso8oygmnu9.cloudfront.net/videos/favourite-thing-about-jesko-final-cta.mp4" },
  { id: 55, title: "Favourite thing about Jesko", src: "https://d6lso8oygmnu9.cloudfront.net/videos/favourite-thing-about-jesko-final-captioned.mp4" },
  { id: 56, title: "Fulfillment", src: "https://d6lso8oygmnu9.cloudfront.net/videos/fulfillment-v4-1.mp4" },
  { id: 57, title: "GT Racing is Loud", src: "https://d6lso8oygmnu9.cloudfront.net/videos/gt-racing-is-loud-fv-captioned.mp4" },
  { id: 58, title: "GT3", src: "https://d6lso8oygmnu9.cloudfront.net/videos/gt3-v10-captioned.mp4" },
  { id: 59, title: "How I became successful", src: "https://d6lso8oygmnu9.cloudfront.net/videos/how-i-became-successful-v8-captioned.mp4" },
  { id: 60, title: "I dont fly empty legs", src: "https://d6lso8oygmnu9.cloudfront.net/videos/i-dont-fly-empty-legs-v8-captioned.mp4" },
  { id: 61, title: "Importance of dressing well", src: "https://d6lso8oygmnu9.cloudfront.net/videos/importance-of-dressing-well-v6.mp4" },
  { id: 62, title: "Importance of dressing well.", src: "https://d6lso8oygmnu9.cloudfront.net/videos/importance-of-dressing-well-v7.mp4" },
  { id: 63, title: "Importance of dressing well", src: "https://d6lso8oygmnu9.cloudfront.net/videos/importance-of-dressing-well-v9.mp4" },
  { id: 64, title: "In car sim", src: "https://d6lso8oygmnu9.cloudfront.net/videos/in-car-sim-v7-captioned.mp4" },
  { id: 65, title: "Jesko Numberplate", src: "https://d6lso8oygmnu9.cloudfront.net/videos/jesko-numberplate-fv-captioned.mp4" },
  { id: 66, title: "Joy of Riding Cars", src: "https://d6lso8oygmnu9.cloudfront.net/videos/joy-of-riding-cars-v9-captioned.mp4" },
  { id: 67, title: "Laser helmet", src: "https://d6lso8oygmnu9.cloudfront.net/videos/laser-helmet-v4-captioned.mp4" },
  { id: 68, title: "M2 review", src: "https://d6lso8oygmnu9.cloudfront.net/videos/m2-reviewv3.mp4" },
  { id: 69, title: "Maintaining relationships", src: "https://d6lso8oygmnu9.cloudfront.net/videos/maintaining-relationships-v5-captioned.mp4" },
  { id: 70, title: "Make Decisions Quicker 1", src: "https://d6lso8oygmnu9.cloudfront.net/videos/make-decisions-quicker-vf-1.mp4" },
  { id: 71, title: "Money management", src: "https://d6lso8oygmnu9.cloudfront.net/videos/money-management.mp4" },
  { id: 72, title: "My Future", src: "https://d6lso8oygmnu9.cloudfront.net/videos/my-future-fv-revised.mp4" },
  { id: 73, title: "My business philosophy", src: "https://d6lso8oygmnu9.cloudfront.net/videos/my-business-philosophy-fv.mp4" },
  { id: 74, title: "Network SOF", src: "https://d6lso8oygmnu9.cloudfront.net/videos/network-sof-v9-revised.mp4" },
  { id: 75, title: "PAGANI VIDEO", src: "https://d6lso8oygmnu9.cloudfront.net/videos/pagani-video-captioned.mp4" },
  { id: 76, title: "People misunderstand me", src: "https://d6lso8oygmnu9.cloudfront.net/videos/people-misunderstand-me-v9-captioned.mp4" },
  { id: 77, title: "Purpose in Life", src: "https://d6lso8oygmnu9.cloudfront.net/videos/purpose-in-life-v4-captioned.mp4" },
  { id: 78, title: "Purpose in Life with caps", src: "https://d6lso8oygmnu9.cloudfront.net/videos/purpose-in-life-with-caps.mp4" },
  { id: 79, title: "Putting Yourself Out There", src: "https://d6lso8oygmnu9.cloudfront.net/videos/putting-yourself-out-there.mp4" },
  { id: 80, title: "Road cars vs Racecars CAP", src: "https://d6lso8oygmnu9.cloudfront.net/videos/road-cars-vs-racecars-fv-cap.mp4" },
  { id: 81, title: "Ruby Story", src: "https://d6lso8oygmnu9.cloudfront.net/videos/ruby-story-final.mp4" },
  { id: 82, title: "Ruby Story with", src: "https://d6lso8oygmnu9.cloudfront.net/videos/ruby-story-v5-with-caption.mp4" },
  { id: 83, title: "Running multiple Businesses", src: "https://d6lso8oygmnu9.cloudfront.net/videos/running-multiple-businesses-v7-captioned.mp4" },
  { id: 84, title: "Saving 1 Month A Year", src: "https://d6lso8oygmnu9.cloudfront.net/videos/saving-1-month-a-year-fv.mp4" },
  { id: 85, title: "Seasonal destinations", src: "https://d6lso8oygmnu9.cloudfront.net/videos/seasonal-destinations-v8-captioned.mp4" },
  { id: 86, title: "Small plane review", src: "https://d6lso8oygmnu9.cloudfront.net/videos/small-plane-review-v9-captioned.mp4" },
  { id: 87, title: "Time Efficiency", src: "https://d6lso8oygmnu9.cloudfront.net/videos/time-efficiency-v10-captioned.mp4" },
  { id: 88, title: "Toxic Mindset", src: "https://d6lso8oygmnu9.cloudfront.net/videos/toxic-mindset-fv.mp4" },
  { id: 89, title: "Vimana Client Story 1", src: "https://d6lso8oygmnu9.cloudfront.net/videos/vimana-client-story-1-v8.mp4" },
  { id: 90, title: "Vimana customer service", src: "https://d6lso8oygmnu9.cloudfront.net/videos/vimana-customer-service.mp4" },
  { id: 91, title: "WITL DUBAI", src: "https://d6lso8oygmnu9.cloudfront.net/videos/witl-dubai-fv.mp4" },
  { id: 92, title: "WITL Dubai", src: "https://d6lso8oygmnu9.cloudfront.net/videos/witl-dubai-fv-rev.mp4" },
  { id: 93, title: "WITL", src: "https://d6lso8oygmnu9.cloudfront.net/videos/witl-v7-captioned.mp4" },
  { id: 94, title: "WITL-Dubai", src: "https://d6lso8oygmnu9.cloudfront.net/videos/witl-dubai-v9.mp4" },
  { id: 95, title: "Wealth shows true character", src: "https://d6lso8oygmnu9.cloudfront.net/videos/wealth-shows-true-character-v6-captioned.mp4" },
  { id: 96, title: "Week in the life", src: "https://d6lso8oygmnu9.cloudfront.net/videos/week-in-the-life-vf3-captioned.mp4" },
  { id: 97, title: "What it takes", src: "https://d6lso8oygmnu9.cloudfront.net/videos/what-it-takes-v2-captioned.mp4" },
  { id: 98, title: "Why I Come to These Rallies", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-i-come-to-these-rallies-v10-captioned.mp4" },
  { id: 99, title: "Why I Drive Like This", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-i-drive-like-this-fv.mp4" },
  { id: 100, title: "Why I Drive Like This", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-i-drive-like-this-fv-pw09.mp4" },
  { id: 101, title: "Why I Drive Like This", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-i-drive-like-this-v7.mp4" },
  { id: 102, title: "Why change is important", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-change-is-important-v6.mp4" },
  { id: 103, title: "Why fly a small plane", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-fly-a-small-plane-v4.mp4" },
  { id: 104, title: "Why he does donuts", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-he-does-donuts-1.mp4" },
  { id: 105, title: "Why he flies Private", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-he-flies-private-fv.mp4" },
  { id: 106, title: "Why sleep is Important", src: "https://d6lso8oygmnu9.cloudfront.net/videos/why-sleep-is-important-v9-captioned.mp4" },
  { id: 107, title: "donuts", src: "https://d6lso8oygmnu9.cloudfront.net/videos/donuts.mp4" },
  { id: 108, title: "past cars", src: "https://d6lso8oygmnu9.cloudfront.net/videos/past-cars.mp4" },
];
