import type { Guide } from "@/content/types";

export const filming: Guide = {
  chapter: "create",
  slug: "filming",
  title: "Viral filming blueprint",
  kicker: "Every shot should give the viewer a reason to keep watching.",
  poster: "EcAAmQII-9c",
  intro: [
    "Great filming is not simply about making something look cinematic. Every shot should help keep the viewer engaged, communicate the story clearly and give the editor everything they need to create a strong final video.",
    "In aviation, you already have access to visually powerful environments.",
  ],
  opener: [
    { kind: "list", style: "beat", items: ["Aircraft.", "Cabins.", "Cockpits.", "Hangars.", "FBOs.", "Runways.", "Aircraft deliveries."] },
    { kind: "p", text: "Your job is to capture them properly." },
  ],
  film: { title: "How to film" },
  sections: [
    {
      n: "01",
      title: "Prepare before you film",
      blocks: [
        {
          kind: "list",
          title: "Before every shoot, know",
          items: [
            "What you are filming",
            "Where you are filming",
            "Who needs to be involved",
            "What equipment you need",
            "Which videos you plan to capture",
            "What supporting footage each video requires",
          ],
        },
        { kind: "p", text: "If you are filming inside a Gulfstream, visiting a Bombardier facility or documenting an aircraft delivery, think through the content opportunities before you arrive." },
        { kind: "aside", text: "Preparation gives you structure. But always be ready to capture something unexpected." },
      ],
    },
    {
      n: "02",
      title: "Pay attention to everything",
      blocks: [
        { kind: "p", text: "When filming, your job is to observe. Stay focused on what is happening through the camera." },
        {
          kind: "list",
          title: "Anticipate",
          items: [
            "Who is about to speak",
            "Where someone is about to move",
            "What someone is about to point at",
            "When an aircraft door is about to open",
            "When the client is about to interact with someone",
            "When something visually interesting is about to happen",
          ],
        },
        { kind: "p", text: "Some of the strongest moments cannot be recreated. You need to be ready for them." },
      ],
    },
    {
      n: "03",
      title: "Keep the camera moving",
      blocks: [
        { kind: "p", text: "Movement creates visual stimulation. Avoid filming everything from one static position." },
        {
          kind: "list",
          title: "Use controlled movement such as",
          style: "tag",
          items: [
            "Slow floating shots",
            "Walking alongside the subject",
            "Following someone into an aircraft",
            "Moving through the cabin",
            "Tracking details",
            "Slow pans",
            "Reactionary camera movements during conversations",
          ],
        },
        { kind: "p", text: "The movement should feel natural. Do not move the camera simply for the sake of moving it." },
      ],
    },
    {
      n: "04",
      title: "Compose every shot properly",
      blocks: [
        { kind: "p", text: "Turn on the grid feature on your phone or camera." },
        {
          kind: "list",
          title: "Pay attention to",
          style: "tag",
          items: ["Eyeline", "Headroom", "Space around the subject", "Symmetry", "Background", "Camera height", "The position of the subject within the frame"],
        },
        { kind: "p", text: "When somebody is speaking directly to camera, aim for a clean frame from roughly the waist or chest upwards unless the concept requires something different." },
        { kind: "p", text: "The viewer should be looking at the subject, not being distracted by poor composition." },
      ],
    },
    {
      n: "05",
      title: "Use lighting to your advantage",
      blocks: [
        { kind: "p", text: "Always understand where your strongest light source is coming from. Where possible, keep the main light in front of the subject rather than directly behind them." },
        {
          kind: "list",
          title: "This is particularly important when filming",
          style: "tag",
          items: ["Inside aircraft cabins", "Inside hangars", "At FBOs", "On the tarmac", "Beside large aircraft windows"],
        },
        { kind: "p", text: "Bright exterior light can easily make someone inside a cabin appear too dark. Always check the image before you start recording." },
      ],
    },
    {
      n: "06",
      title: "Test your audio",
      blocks: [
        { kind: "p", text: "Poor audio can ruin otherwise strong footage." },
        {
          kind: "checklist",
          title: "Before filming",
          items: [
            "Make sure microphones are connected",
            "Check they are recording",
            "Check microphone placement",
            "Make sure the microphone is not rubbing against clothing",
            "Monitor background noise",
            "Use wind protection outdoors where required",
            "Check the audio again throughout the shoot",
          ],
        },
        { kind: "p", text: "Do not assume that because the microphone worked at the beginning it is still working an hour later." },
        { kind: "p", text: "If you are standing beside an aircraft, inside a busy hangar or filming outdoors at an airport, audio becomes even more important." },
      ],
    },
    {
      n: "07",
      title: "Capture people speaking cleanly",
      blocks: [
        { kind: "p", text: "If someone is speaking, prioritise getting a clear shot of them." },
        { kind: "list", title: "Focus on", style: "tag", items: ["Good lighting", "Clean composition", "Correct eyeline", "Clear audio", "A steady image"] },
        { kind: "p", text: "Do not constantly chase B roll while an important conversation is happening. Capture the dialogue properly first. You can collect supporting footage afterwards." },
      ],
    },
    {
      n: "08",
      title: "Direct with confidence",
      blocks: [
        { kind: "p", text: "If someone is appearing on camera, do not expect them to automatically know what you need. Tell them clearly." },
        {
          kind: "list",
          title: "You may need to",
          items: [
            "Change where they stand",
            "Ask them to repeat a line",
            "Simplify what they are saying",
            "Increase their energy",
            "Slow them down",
            "Move them into better lighting",
            "Ask them to demonstrate something again",
            "Change their position relative to the aircraft",
            "Show them exactly how you want something delivered",
          ],
        },
        { kind: "p", text: "Even highly experienced founders, pilots, brokers or executives may not be experienced on camera. Your job is to help them look their best." },
      ],
    },
    {
      n: "09",
      title: "Repeat the shot when necessary",
      blocks: [
        { kind: "p", text: "If something is wrong, film it again." },
        {
          kind: "list",
          title: "This could include",
          style: "tag",
          items: [
            "A mistake in speech",
            "A stutter",
            "A voice crack",
            "Poor lighting",
            "Bad framing",
            "Background interference",
            "Audio problems",
            "Someone walking through the shot",
            "An awkward camera movement",
          ],
        },
        { kind: "p", text: "Do not accept weak footage simply because you feel uncomfortable asking someone to repeat something." },
        { kind: "aside", text: "It is easier to repeat a line for thirty seconds during filming than discover the problem during editing." },
      ],
    },
    {
      n: "10",
      title: "Capture multiple angles",
      blocks: [
        { kind: "p", text: "Do not give your editor one version of everything." },
        {
          kind: "list",
          title: "If you are filming someone walking towards a Gulfstream, consider capturing",
          items: [
            "A wide establishing shot",
            "A closer side angle",
            "A shot from behind",
            "A shot walking in front of them",
            "A close up of their hand opening the aircraft door",
            "A shot from inside the aircraft as they enter",
          ],
        },
        { kind: "p", text: "The more useful angles you have, the more visual variation can be created during the edit." },
        {
          kind: "clips",
          title: "Three walkarounds, from the library",
          note: "Count the angles in each.",
          items: [
            { id: "EcAAmQII-9c", caption: "Touring a $50,000,000 corporate jet" },
            { id: "KGVOiwba6gA", caption: "Touring a $60,000,000 corporate jet" },
            { id: "b_GjZ5I4LH4", caption: "Touring a $10,000,000 corporate jet" },
          ],
        },
      ],
    },
    {
      n: "11",
      title: "Capture B roll after the main content",
      blocks: [
        { kind: "p", text: "Once the main dialogue or action is complete, deliberately capture supporting footage." },
        {
          kind: "list",
          title: "For aviation, this could include",
          style: "tag",
          items: [
            "Aircraft exterior",
            "Tail",
            "Engines",
            "Wings",
            "Windows",
            "Cockpit",
            "Seats",
            "Cabin details",
            "Lighting controls",
            "Tables",
            "Galley",
            "Luggage compartment",
            "Crew preparation",
            "Passenger boarding",
            "Aircraft taxiing",
            "Hangar activity",
            "FBO environment",
            "Close ups of interesting details",
          ],
        },
        { kind: "questions", title: "Ask yourself", items: ["What is being discussed in the video?"] },
        { kind: "p", text: "Then capture footage that allows the viewer to actually see it." },
      ],
    },
    {
      n: "12",
      title: "Vary your shots",
      blocks: [
        { kind: "p", text: "Avoid capturing every piece of footage from the same distance." },
        {
          kind: "list",
          title: "Use a combination of",
          style: "tag",
          items: [
            "Wide shots",
            "Medium shots",
            "Close ups",
            "Tracking shots",
            "Panning shots",
            "Low angles",
            "High angles",
            "Shots from behind the subject",
            "Shots walking alongside the subject",
            "Detail shots",
            "Reactive camera movement",
          ],
        },
        {
          kind: "shots",
          title: "Four sizes, same subject",
          items: [
            { label: "Wide", size: "wide", text: "The aircraft, the hangar, the person in the space. Establishes where we are." },
            { label: "Medium", size: "medium", text: "Waist up. The default for someone speaking to camera." },
            { label: "Close", size: "close", text: "The face. Reactions, emphasis, the important sentence." },
            { label: "Detail", size: "detail", text: "Hands, controls, materials. The thing you want noticed." },
          ],
          note: "Grid on. Eyeline on the upper third. Cut between at least three of these in every video.",
        },
        { kind: "p", text: "A viewer should continuously receive new visual information." },
      ],
    },
    {
      n: "13",
      title: "Stay loose",
      blocks: [
        { kind: "p", text: "Do not hold the camera with a stiff wrist. Your movements should feel controlled and fluid." },
        {
          kind: "list",
          title: "This is particularly important when",
          items: [
            "Walking through an aircraft",
            "Following someone through a hangar",
            "Tracking a person boarding",
            "Moving around a cabin",
            "Reacting quickly during conversations",
          ],
        },
        { kind: "p", text: "The camera should feel like it is naturally following the action." },
      ],
    },
    {
      n: "14",
      title: "Use your lenses with purpose",
      blocks: [
        { kind: "p", text: "Different lenses create different results." },
        {
          kind: "split",
          a: { label: "Use wider lenses to show", items: ["The full cabin", "A confined interior", "A large environment", "Someone walking through an aircraft"] },
          b: { label: "Use tighter lenses for", items: ["Details", "Faces", "Aircraft features", "Hands", "Controls", "Materials", "Small elements you want the audience to notice"] },
        },
        {
          kind: "lens",
          title: "From the same spot",
          wide: "Takes the whole cabin: every seat, the length of it, the person walking through.",
          tight: "Takes one control on the panel, and nothing else. The viewer looks where you looked.",
        },
        { kind: "p", text: "Avoid unnecessary extreme zooms. Choose the lens based on what the viewer needs to see." },
      ],
    },
    {
      n: "15",
      title: "Keep your equipment ready",
      blocks: [
        {
          kind: "checklist",
          title: "Before filming",
          items: [
            "Clean your lens",
            "Check your battery",
            "Check storage",
            "Check microphones",
            "Check lighting",
            "Check your frame rate",
            "Check your resolution",
            "Make sure HDR settings are correct for your workflow",
          ],
        },
        { kind: "p", text: "Keep your equipment ready throughout the shoot. Small technical mistakes can make otherwise valuable footage unusable." },
      ],
    },
    {
      n: "16",
      title: "Film with the edit in mind",
      blocks: [
        { kind: "p", text: "Do not think of filming and editing as completely separate processes. While filming, think about how the final video will be cut together." },
        {
          kind: "questions",
          title: "Ask",
          items: [
            "Where will the editor need B roll?",
            "Where could we change angle?",
            "What visual supports this sentence?",
            "Do we have an establishing shot?",
            "Do we have enough close ups?",
            "Do we have footage to cover cuts in dialogue?",
            "Do we have a strong opening visual?",
          ],
        },
        { kind: "p", text: "The better the footage is planned, the stronger the edit can become." },
      ],
    },
    {
      title: "The Tilted Needle filming standard",
      blocks: [
        {
          kind: "checklist",
          title: "Before leaving a shoot, make sure you have",
          items: [
            "Clean dialogue",
            "Clear audio",
            "Good lighting",
            "Strong composition",
            "Multiple angles",
            "Relevant B roll",
            "Close ups",
            "Wide shots",
            "Movement",
            "Opening visuals",
            "Enough footage to cover the entire story",
          ],
        },
      ],
    },
  ],
  rule: [
    { kind: "p", text: "Do not simply record what is happening." },
    { kind: "p", text: "Capture it in a way that gives the viewer a reason to keep watching." },
  ],
};
