import type { Guide } from "@/content/types";

export const videoStyle: Guide = {
  chapter: "create",
  slug: "video-style",
  title: "Choose your video style",
  kicker: "The idea comes first. Then the format that makes it most interesting to watch.",
  poster: "93f2iVn6rIc",
  intro: [
    "Once you have the idea, the next step is deciding how that idea should be presented.",
    "In aviation, you often have access to highly visual environments: aircraft, hangars, cabins, airports, clients and experiences that most people never get to see. The format you choose should take advantage of that access.",
    "The same topic could be filmed as a Q&A inside a Gulfstream, a Day In The Life at an FBO, a reaction to a new Bombardier launch or a short documentary following an aircraft delivery.",
  ],
  film: { title: "Choose your video style" },
  sections: [
    {
      n: "01",
      title: "Skits",
      blocks: [
        { kind: "p", text: "Skits use relatable aviation scenarios, humour and exaggeration to create entertaining content. They work particularly well around situations people within the industry recognise immediately." },
        {
          kind: "list",
          title: "For example",
          items: [
            "Different types of private jet passengers",
            "What charter clients think happens versus what actually happens",
            "Different types of aircraft buyers",
            "Things brokers hear every day",
            "Common requests from first time private flyers",
            "The difference between commercial and private aviation",
          ],
        },
        { kind: "p", text: "Strong skits usually have a simple setup, an instantly recognisable scenario and a clear payoff." },
        { kind: "aside", text: "The content should still feel relevant to your brand rather than creating comedy purely for the sake of it." },
      ],
    },
    {
      n: "02",
      title: "Day in the life",
      blocks: [
        { kind: "p", text: "Aviation naturally lends itself to Day In The Life content because the audience gets access to environments they rarely see." },
        {
          kind: "list",
          title: "This could follow",
          style: "tag",
          items: [
            "A private jet broker",
            "A charter broker",
            "A pilot",
            "An aircraft sales professional",
            "An aviation entrepreneur",
            "A flight operations team",
            "A day at an FBO",
            "A major aviation event",
            "An aircraft delivery",
            "A client trip",
            "A day travelling between cities by private jet",
          ],
        },
        { kind: "p", text: "Show the real journey." },
        {
          kind: "list",
          style: "beat",
          items: ["The aircraft arriving.", "The terminal.", "The crew.", "The meetings.", "The problems.", "The decisions.", "The unexpected moments.", "The destination."],
        },
        { kind: "aside", text: "Do not simply film a collection of luxury shots. There should be a reason for the viewer to stay until the end." },
        {
          kind: "clips",
          title: "Two days, from the library",
          items: [
            { id: "93f2iVn6rIc", caption: "A day in the life of a content producer" },
            { id: "w01i_-g_jYs", caption: "A week in the life at Tilted Needle" },
          ],
        },
      ],
    },
    {
      n: "03",
      title: "Customer interactions",
      blocks: [
        { kind: "p", text: "Real customer interactions can make aviation content feel significantly more authentic." },
        {
          kind: "list",
          title: "This could include",
          items: [
            "A client seeing their aircraft for the first time",
            "A customer choosing between different cabin configurations",
            "A charter client asking a genuine question",
            "An aircraft handover",
            "Someone experiencing private aviation for the first time",
            "A buyer inspecting an aircraft",
            "A conversation inside a showroom or hangar",
            "A client reacting to a particular aircraft feature",
          ],
        },
        { kind: "p", text: "The value comes from the interaction being real. The audience gets to experience a moment they would normally never have access to." },
        { kind: "aside", text: "Always make sure you have permission before filming or publishing customer interactions." },
      ],
    },
    {
      n: "04",
      title: "Reaction videos",
      blocks: [
        { kind: "p", text: "Aviation constantly creates opportunities for reaction content." },
        {
          kind: "list",
          title: "You could react to",
          style: "tag",
          items: [
            "A newly announced private jet",
            "A manufacturer unveiling a new aircraft",
            "A new Gulfstream or Bombardier model",
            "An unusual aircraft configuration",
            "A viral aviation video",
            "An airport story",
            "A major industry announcement",
            "New cabin technology",
            "A record breaking flight",
            "An unusual landing",
            "A new aviation regulation",
          ],
        },
        { kind: "p", text: "The reaction itself is not enough. Your expertise is what makes the video valuable." },
        {
          kind: "questions",
          title: "Explain what matters",
          items: [
            "What is unusual?",
            "Why is the announcement important?",
            "What does the general public misunderstand?",
            "What would someone inside the industry notice immediately?",
          ],
        },
        { kind: "p", text: "Give the viewer information they would not get from simply watching the original clip." },
        {
          kind: "clips",
          title: "Reactions, from the library",
          items: [
            { id: "Q6w29LCIz04", caption: "Reacting to Koenigsegg's closed-wing patent" },
            { id: "HEdkGMatZN0", caption: "Reacting to an Airbus corporate jet" },
            { id: "OPeLbjGVQ04", caption: "Reacting to a viral F1 picture" },
          ],
        },
      ],
    },
    {
      n: "05",
      title: "Educational videos",
      blocks: [
        { kind: "p", text: "Aviation contains countless subjects the general public finds interesting but knows very little about. Use educational content to make complicated topics simple." },
        {
          kind: "questions",
          title: "For example",
          items: [
            "How far can a private jet actually fly?",
            "Why do some private jets need fuel stops?",
            "What determines the range of an aircraft?",
            "What is an empty leg?",
            "Can you change destination while already flying?",
            "Why do private jets have different window shapes?",
            "How does aircraft depreciation work?",
            "What makes one aircraft harder to sell than another?",
            "What is the difference between a Gulfstream and a Bombardier?",
            "Why can two aircraft of a similar size have completely different capabilities?",
          ],
        },
        { kind: "p", text: "Focus on one clear question or idea per video. Make the viewer feel like they learned something they would not normally know." },
        {
          kind: "clips",
          title: "One question each, from the library",
          items: [
            { id: "3mG5AduZ-OY", caption: "What is a high-performance takeoff?" },
            { id: "WtFrrO8SvTE", caption: "What do the numbers on corporate jets mean?" },
            { id: "vvfyWPtViUY", caption: "What does it really cost to own a $15M private jet?" },
          ],
        },
      ],
    },
    {
      n: "06",
      title: "Short documentaries",
      blocks: [
        { kind: "p", text: "Short documentary content is particularly powerful in aviation because so many interesting stories happen behind the scenes." },
        {
          kind: "list",
          title: "You could document",
          items: [
            "The purchase of an aircraft",
            "An aircraft delivery",
            "The specification process",
            "A major charter journey",
            "The restoration of an aircraft",
            "The development of a new aircraft",
            "A significant business deal",
            "A day at an aviation event",
            "The journey of building an aviation company",
            "The story behind a particular aircraft",
            "An unexpected problem during a trip",
          ],
        },
        { kind: "p", text: "Do not automatically start at the beginning. Start with the most interesting moment." },
        { kind: "lines", title: "For example", mode: "spoken", items: ["The deal nearly collapsed 24 hours before the aircraft was delivered."] },
        { kind: "p", text: "Then explain how you got there. Give the viewer a reason to want the rest of the story." },
        {
          kind: "clips",
          title: "Stories, from the library",
          items: [
            { id: "qj-bCVEaxko", caption: "The story of my first ever jet sale" },
            { id: "iCZ5Nhl9mMk", caption: "To Germany for a conference and home the same day" },
          ],
        },
      ],
    },
    {
      n: "07",
      title: "Trends",
      blocks: [
        { kind: "p", text: "Trends allow you to connect aviation with conversations that already have attention." },
        {
          kind: "list",
          title: "This could include",
          style: "tag",
          items: [
            "Trending video formats",
            "Popular audio",
            "Current aviation news",
            "Major aircraft launches",
            "Industry events",
            "Celebrity aviation stories, where appropriate and publicly available",
            "New technology",
            "Airport news",
            "Travel trends",
            "Major cultural moments",
          ],
        },
        { kind: "p", text: "Do not force your brand into every trend." },
        {
          kind: "questions",
          title: "Ask",
          items: [
            "Can we make this relevant to aviation?",
            "Can we add expertise?",
            "Can we show something the public normally cannot see?",
            "Does it fit how we want the company to be perceived?",
          ],
        },
        { kind: "p", text: "If the answer is no, leave it." },
      ],
    },
    {
      n: "08",
      title: "Q&A with B roll",
      blocks: [
        { kind: "p", text: "Q&A With B Roll is one of the strongest formats for aviation because the aircraft itself can help tell the story." },
        { kind: "p", text: "Start with a question your audience genuinely wants answered. Then answer it clearly while supporting the explanation with relevant footage." },
        {
          kind: "pairs",
          title: "For example",
          aLabel: "If you are explaining",
          bLabel: "Show",
          items: [
            { a: "The difference between a Gulfstream and a Bombardier", b: "The aircraft, cabin, windows, cockpit or features you are discussing." },
            { a: "Aircraft range", b: "The aircraft alongside maps or relevant journey footage." },
            { a: "Cabin configuration", b: "The different areas of the cabin." },
            { a: "Charter operations", b: "The terminal, crew preparation and aircraft turnaround." },
            { a: "Aircraft maintenance", b: "The hangar, engineering environment or relevant components where appropriate." },
          ],
        },
        { kind: "aside", text: "The B roll should help the viewer understand what you are saying. It should not simply fill the screen." },
        {
          kind: "list",
          title: "Questions can come from",
          style: "tag",
          items: [
            "Customers",
            "Comments",
            "Charter clients",
            "Aircraft buyers",
            "Industry misconceptions",
            "Sales conversations",
            "Frequently asked questions",
            "Previous videos",
            "Your own team",
          ],
        },
        { kind: "p", text: "One strong question can often lead to several future videos." },
        {
          kind: "clips",
          title: "Questions answered with the aircraft in shot",
          items: [
            { id: "kgexit7JaUA", caption: "How to buy a $25,000,000 corporate jet" },
            { id: "EcAAmQII-9c", caption: "Touring a $50,000,000 corporate jet" },
          ],
        },
      ],
    },
    {
      title: "How to choose the right format",
      blocks: [
        {
          kind: "checklist",
          title: "Before filming, ask",
          items: [
            "What is the actual idea?",
            "What aircraft, location or environment do we have access to?",
            "Who is the strongest person to deliver it?",
            "Would showing the aircraft be more powerful than simply talking about it?",
            "Is there a real customer interaction we can capture?",
            "Would this work better as a story?",
            "Could we demonstrate what we are explaining?",
            "Is there something happening behind the scenes that the public rarely sees?",
            "Does the idea naturally suit education, entertainment or storytelling?",
            "What format gives the viewer the strongest reason to continue watching?",
          ],
        },
        { kind: "p", text: "Do not make every video look the same. Aviation gives you access to aircraft, environments and experiences that are naturally interesting. Use them." },
      ],
    },
  ],
  rule: [
    { kind: "p", text: "The idea comes first." },
    { kind: "p", text: "Then choose the format that makes the audience feel like they are getting access to a world they normally would not see." },
  ],
};
